// Pulls the game engine out of the original single-file web app so the new
// app shell can run the real 3D games without editing their code.
//
//   node scripts/extract-engine.mjs [path/to/BAYANIHanda-Game-Library.html]
//
// Writes:
//   public/engine/three.min.js   Three.js r1xx build that shipped with the web app
//   public/engine/games.js       Logic, App, AimController and every 3D game, untouched
//   src/engine/screens.html      In-game screens (canvas + HUD), result screens the
//                                games write into, and the go bag item modal
//
// Everything else in the web app (hub, pillar lists, how-to pages, scorecard,
// settings and about modals) is replaced by the new design in src/.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const src = resolve(root, process.argv[2] || 'project/uploads/BAYANIHanda-Game-Library.html');
const html = readFileSync(src, 'utf8');

function scriptAfter(marker) {
  const at = html.indexOf(marker);
  if (at < 0) throw new Error('Marker not found: ' + marker);
  const open = html.lastIndexOf('<script>', at);
  const close = html.indexOf('</script>', at);
  return html.slice(open + '<script>'.length, close);
}

const three = scriptAfter('Three.js Authors');
const games = scriptAfter('BYANI-Handa Games');

// Sections never nest in the web app, so a lazy match to </section> is safe.
const sections = [];
const re = /<section id="(screen-[a-z0-9-]+)" class="screen( g3d)?">[\s\S]*?<\/section>/g;
let m;
while ((m = re.exec(html))) {
  const id = m[1];
  const isGame = !!m[2];
  const isResult = /-(result|win)$/.test(id);
  if (isGame || isResult) sections.push({ id, kind: isGame ? 'game' : 'result', markup: m[0] });
}

function blockById(id) {
  const at = html.indexOf('<div id="' + id + '"');
  if (at < 0) throw new Error('Block not found: ' + id);
  const end = html.indexOf('</div></div>', at) + '</div></div>'.length;
  return html.slice(at, end);
}

const games3d = sections.filter((s) => s.kind === 'game');
const results = sections.filter((s) => s.kind === 'result');

const out = [
  '<!-- GENERATED by scripts/extract-engine.mjs from the original web app. Do not edit by hand. -->',
  '<!-- In-game screens: canvas + HUD, shown one at a time by the engine bridge. -->',
  ...games3d.map((s) => s.markup),
  '<!-- Result screens stay hidden: the games write stars, lines and badge notes here,',
  '     and the new Results screen reads them back. -->',
  '<div class="engine-results" hidden>',
  ...results.map((s) => s.markup),
  '</div>',
  '<!-- Go bag item card (opened by the game while playing). -->',
  blockById('modal-info'),
  '',
].join('\n');

mkdirSync(resolve(root, 'public/engine'), { recursive: true });
mkdirSync(resolve(root, 'src/engine'), { recursive: true });
writeFileSync(resolve(root, 'public/engine/three.min.js'), three.trim() + '\n');
writeFileSync(resolve(root, 'public/engine/games.js'), games.trim() + '\n');
writeFileSync(resolve(root, 'src/engine/screens.html'), out);

console.log('three.min.js  ' + (three.length / 1024).toFixed(0) + ' KB');
console.log('games.js      ' + (games.length / 1024).toFixed(0) + ' KB');
console.log('screens.html  ' + games3d.length + ' game screens, ' + results.length + ' result screens');
